---
- include: install.yml
  when: install|bool

- include: configure.yml
  when: configure|bool

- include: nerdtree.yml
  when: nerdtree|bool

- include: themes.yml
  when: install_themes|bool

- include: icons.yml
  when: icons|bool

- include: powerline.yml
  when: powerline|bool

- include: syntax.yml

- include: support_golang.yml
  when: golang|bool
