---
- name: "Get themes"
  git:
    repo: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
  with_items: "{{ themes }}"


- name: "Install themes"
  copy:
    remote_src: yes
    src: "/tmp/{{ item.name }}/{{ item.file }}"
    dest: "~/.vim/colors/{{ item.name }}.vim"
  with_items: "{{ themes }}"
  when: ansible_version.major >= 2 


- name: "Install themes (ansible version < 2)"
  command:
    "cp /tmp/{{ item.name }}/{{ item.file }} ~/.vim/colors/{{ item.name }}.vim"
  with_items: "{{ themes }}"
  when: ansible_version.major < 2


- name: "Clean up downloaded themes"
  file:
    path: "/tmp/{{ item.name }}"
    state: absent
  with_items: "{{ themes }}"

