---
# TODO:
# 1. check it on Debian
# 2. Check it on centos
- name: "Install dependencies (debial-family)"
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages.deb }}"
  when: "{{ ansible_architecture == 'x86_64' and ansible_os_family == 'Debian' }}"
  become: True


- name: "Copy binaries"
  copy:
    src: "{{ item }}"
    dest: "{{ bin_files.dir }}"
    owner: "{{ bin_files.owner }}"
    group: "{{ bin_files.group }}"
    mode: "{{ bin_files.mode }}"
  with_items: "{{ bin_files.binaries }}"
  become: True


- name: "Create directory for IOU images"
  file:
    path: "{{ ansible_env.HOME }}/{{ images.directory }}"
    mode: "{{ images.mode }}"
    state: directory


- name: "Copy IOU images"
  copy:
    src: "{{ iou_images_dir }}/"
    dest: "{{ images.directory }}"


# To avoid error: error while loading shared libraries: libcrypto.so.4: cannot open shared object file: No such file or directory
# Create symlink to 32-bit library
- name: "Create symlink to libssl"
  file:
    src: "/lib/i386-linux-gnu/libssl.so.1.0.0"
    dest: "/lib/libcrypto.so.4"
    state: link
  when: "{{ ansible_architecture == 'x86_64' and ansible_os_family == 'Debian' }}"
  become: True

